<?xml version="1.0" encoding="utf-8"?><Database Name="StableBase" Class="StableBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\StableBase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StableBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Horse" Member="Horses">
    <Type Name="Horse">
      <Column Name="HorseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HorseName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HorsePicture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HorseSize" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="HorseWeight" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="HorseRidingSchool" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="HorseShowJumping" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="HorseDressage" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="HorseRacing" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Association Name="Horse_HorseTask" Member="HorseTasks" ThisKey="HorseID" OtherKey="HorseID" Type="HorseTask" />
    </Type>
  </Table>
  <Table Name="dbo.Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaskName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Task_HorseTask" Member="HorseTasks" ThisKey="TaskID" OtherKey="TaskID" Type="HorseTask" />
    </Type>
  </Table>
  <Table Name="dbo.HorseTask" Member="HorseTasks">
    <Type Name="HorseTask">
      <Column Name="HorseTaskID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HorseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HorseTaskIsDaily" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HorseTaskIsMorning" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HorseTaskStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HorseTaskEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HorseTaskNotes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Horse_HorseTask" Member="Horse" ThisKey="HorseID" OtherKey="HorseID" Type="Horse" IsForeignKey="true" />
      <Association Name="Task_HorseTask" Member="Task" ThisKey="TaskID" OtherKey="TaskID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NewsText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>