//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableBase.NewServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewServiceReference.NewWebServiceSoap")]
    public interface NewWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        StableBase.NewServiceReference.HelloWorldResponse HelloWorld(StableBase.NewServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<StableBase.NewServiceReference.HelloWorldResponse> HelloWorldAsync(StableBase.NewServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetNewsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNews", ReplyAction="*")]
        StableBase.NewServiceReference.GetNewsResponse GetNews(StableBase.NewServiceReference.GetNewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNews", ReplyAction="*")]
        System.Threading.Tasks.Task<StableBase.NewServiceReference.GetNewsResponse> GetNewsAsync(StableBase.NewServiceReference.GetNewsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public StableBase.NewServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(StableBase.NewServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public StableBase.NewServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(StableBase.NewServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNews", Namespace="http://tempuri.org/", Order=0)]
        public StableBase.NewServiceReference.GetNewsRequestBody Body;
        
        public GetNewsRequest() {
        }
        
        public GetNewsRequest(StableBase.NewServiceReference.GetNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNewsRequestBody {
        
        public GetNewsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public StableBase.NewServiceReference.GetNewsResponseBody Body;
        
        public GetNewsResponse() {
        }
        
        public GetNewsResponse(StableBase.NewServiceReference.GetNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StableBase.NewServiceReference.ArrayOfString GetNewsResult;
        
        public GetNewsResponseBody() {
        }
        
        public GetNewsResponseBody(StableBase.NewServiceReference.ArrayOfString GetNewsResult) {
            this.GetNewsResult = GetNewsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NewWebServiceSoapChannel : StableBase.NewServiceReference.NewWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewWebServiceSoapClient : System.ServiceModel.ClientBase<StableBase.NewServiceReference.NewWebServiceSoap>, StableBase.NewServiceReference.NewWebServiceSoap {
        
        public NewWebServiceSoapClient() {
        }
        
        public NewWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StableBase.NewServiceReference.HelloWorldResponse StableBase.NewServiceReference.NewWebServiceSoap.HelloWorld(StableBase.NewServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            StableBase.NewServiceReference.HelloWorldRequest inValue = new StableBase.NewServiceReference.HelloWorldRequest();
            inValue.Body = new StableBase.NewServiceReference.HelloWorldRequestBody();
            StableBase.NewServiceReference.HelloWorldResponse retVal = ((StableBase.NewServiceReference.NewWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StableBase.NewServiceReference.HelloWorldResponse> StableBase.NewServiceReference.NewWebServiceSoap.HelloWorldAsync(StableBase.NewServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<StableBase.NewServiceReference.HelloWorldResponse> HelloWorldAsync() {
            StableBase.NewServiceReference.HelloWorldRequest inValue = new StableBase.NewServiceReference.HelloWorldRequest();
            inValue.Body = new StableBase.NewServiceReference.HelloWorldRequestBody();
            return ((StableBase.NewServiceReference.NewWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StableBase.NewServiceReference.GetNewsResponse StableBase.NewServiceReference.NewWebServiceSoap.GetNews(StableBase.NewServiceReference.GetNewsRequest request) {
            return base.Channel.GetNews(request);
        }
        
        public StableBase.NewServiceReference.ArrayOfString GetNews() {
            StableBase.NewServiceReference.GetNewsRequest inValue = new StableBase.NewServiceReference.GetNewsRequest();
            inValue.Body = new StableBase.NewServiceReference.GetNewsRequestBody();
            StableBase.NewServiceReference.GetNewsResponse retVal = ((StableBase.NewServiceReference.NewWebServiceSoap)(this)).GetNews(inValue);
            return retVal.Body.GetNewsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StableBase.NewServiceReference.GetNewsResponse> StableBase.NewServiceReference.NewWebServiceSoap.GetNewsAsync(StableBase.NewServiceReference.GetNewsRequest request) {
            return base.Channel.GetNewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StableBase.NewServiceReference.GetNewsResponse> GetNewsAsync() {
            StableBase.NewServiceReference.GetNewsRequest inValue = new StableBase.NewServiceReference.GetNewsRequest();
            inValue.Body = new StableBase.NewServiceReference.GetNewsRequestBody();
            return ((StableBase.NewServiceReference.NewWebServiceSoap)(this)).GetNewsAsync(inValue);
        }
    }
}
